# This is an example of what an '_config.yml' file should look like
# when using jekyll-shell-theme. You should use this as a guide or
# just copy+paste it and modify some of the content to begin with.

title: Goldrush Gauntlet
email: cyberhawks@ung.edu
description: >- # this means to ignore newlines until "baseurl:"
  A paragraph describing your webpage.
baseurl: "/" # the subpath of your site
url: "https://ggctf.cyberhawks.org" # the base hostname & protocol for your site
github_username: cyberhawks-ung

# Required plugins for the theme to work properly
plugins:
  - github-pages
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: "cyberhawks-ung/jekyll-ggctf-theme"

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md

# controls how big the shell and font looks
font-size: small # options: [small] or [large]

